1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,9 +2,10 @@ name: "Release Workflow"
 on:
   push:
     tags:
-      - "v[0-9]+.[0-9]+.[0-9]+"
-      - "v[0-9]+.[0-9]+.[0-9]+-M[0-9]+"
-      - "v[0-9]+.[0-9]+.[0-9]+-RC[0-9]+"
+      # - "v[0-9]+.[0-9]+.[0-9]+"
+      # - "v[0-9]+.[0-9]+.[0-9]+-M[0-9]+"
+      # - "v[0-9]+.[0-9]+.[0-9]+-RC[0-9]+"
+      - "**"
     branches:
       - "master"
       - "main"
@@ -15,49 +16,44 @@ jobs:
     name: "release-tag-job-name"
     runs-on: ubuntu-latest
     outputs:
-      tag-value: ${{ steps.check-tag.outputs.tag-value }}
+      context_tag: ${{ steps.git-context.outputs.tag }}
+      context_ref_type: ${{ steps.git-context.outputs.ref_type }}
+      context_ref_name: ${{ steps.git-context.outputs.ref_name }}
+      context_sha: ${{ steps.git-context.outputs.sha }}
+      context_shaShort: ${{ steps.git-context.outputs.shaShort }}
+      context_context: ${{ steps.git-context.outputs.context }}
     steps:
-      - name: Get tag
-        id: check-tag
-        continue-on-error: true
-        run: |
-          # echo 'refs/tags/v0.3.2-RC1' | sed  's/refs\/tags\/v\(.*\)$/\1/;tx;q100;:x' #if [ $? -eq 0 ]; then else fi
-          echo ::set-output name=tag-value::$(echo ${{ github.event.ref }} | sed  's/refs\/tags\/v\(.*\)$/\1/;tx;q100;:x')
-          # ... check if everything  clean to make a release with this tag
+      - name: Get git context
+        id: git-context
 
-      - name: INFO TAG VALUE
-        if: steps.check-tag.outcome == 'success'
-        run: echo "Tag '${{ steps.check-tag.outputs.tag-value }}' will be publish."
-      - name: STOP RELEASE WORKFLOW
-        if: steps.check-tag.outcome == 'failure'
         run: |
-          echo The git refs '${{ github.event.ref }}' is not a proper tag to publish.
-          exit 1
-
-      - name: TEST
-        run: |
-          echo '{
-            "event_name": "${{ github.event_name }}",
-            "ref": "${{ github.ref }}",
-            "ref_type": "${{ github.ref_type }}",
-            "ref_name": "${{ github.ref_name }}",
-            "sha": "${{ github.sha }}",
-            "github": "${{ github }}"
+          echo ::set-output name=context_tag::$(echo ${{ github.event.ref }} | sed  's/refs\/tags\/v\(.*\)$/\1/;tx;q100;:x')
+          echo ::set-output name=context_ref_type::${{ github.ref_type }}
+          echo ::set-output name=context_ref_name::${{ github.ref_name }}
+          echo ::set-output name=context_sha::${{ github.sha }}
+          echo ::set-output name=context_shaShort::$(${{ github.sha }} | head -c 7)
+          CONTEXT='{ ${{ steps.git-context.outputs.tag-value }}
+            "ref_type": "${{ steps.git-context.outputs.context_ref_type }}",
+            "ref_name": "${{ steps.git-context.outputs.context_ref_name }}",
+            "sha": "${{ steps.git-context.outputs.context_sha }}",
+            "shaShort": "${{ steps.git-context.outputs.context_shaShort }}
           }'
+          echo ::set-output name=context_context::$CONTEXT
 
-      - name: Dump GitHub context
-        id: github_context_step
-        run: echo '${{ toJSON(github) }}'
-      - name: Dump job context
-        run: echo '${{ toJSON(job) }}'
-      - name: Dump steps context
-        run: echo '${{ toJSON(steps) }}'
-      - name: Dump runner context
-        run: echo '${{ toJSON(runner) }}'
-      - name: Dump strategy context
-        run: echo '${{ toJSON(strategy) }}'
-      - name: Dump matrix context
-        run: echo '${{ toJSON(matrix) }}'
+      #   continue-on-error: true
+      #   run: |
+      #     # echo 'refs/tags/v0.3.2-RC1' | sed  's/refs\/tags\/v\(.*\)$/\1/;tx;q100;:x' # if [ $? -eq 0 ]; then else fi
+      #     echo ::set-output name=tag-value::$(echo ${{ github.event.ref }} | sed  's/refs\/tags\/v\(.*\)$/\1/;tx;q100;:x')
+      #     # ... check if everything  clean to make a release with this tag
+
+      # - name: INFO TAG VALUE
+      #   if: steps.check-tag.outcome == 'success'
+      #   run: echo "Tag '${{ steps.check-tag.outputs.tag-value }}' will be publish."
+      # - name: STOP RELEASE WORKFLOW
+      #   if: steps.check-tag.outcome == 'failure'
+      #   run: |
+      #     echo The git refs '${{ github.event.ref }}' is not a proper tag to publish.
+      #     exit 1
 
       - name: Set ENV & TAG convention
         run: |
@@ -67,7 +63,7 @@ jobs:
               tag=$(echo $GITHUB_REF_NAME)
               echo "TAG=$tag" >> $GITHUB_ENV
               echo "::set-output name=tag::$tag"
-          elif [[ ${GITHUB_REF_TYPE} == "tag" ]]
+          else
               revCount=$(git rev-list HEAD --count)
               shaShort=$(git rev-parse --short HEAD)
               tag="${branchPrefix}-${revCount}-${shaShort}"
